### ISSUE TITLE
when I execute the command `docker-compose up -d`  in directory example 

### ISSUE THREAD

**Issue by ZhuoSiChen** [ysugimoto/lua-resty-grpc-gateway#20]
when I execute the command `docker-compose up -d`  in directory example 
Report that:
ERROR: Service 'server' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder609038124/app: no such file or directory

**Comment by kmasuda050** [comment]
Please execute `make all` before `docker-compose up -d` .
See https://github.com/ysugimoto/lua-resty-grpc-gateway/tree/master/example#how-to-build

**Comment by ysugimoto** [comment]
Yes, you need to execute `make all` before `docker-compose up -d`.
