### ISSUE TITLE
Import statements in protobuf causes find method failure

### ISSUE THREAD

**Issue by kgoguevgoget** [ysugimoto/lua-resty-grpc-gateway#6]
As a quick test, I wanted to see if the proto file could contain import statements in order to be able to use the well known protobuf types from google. This is using the examples folder from the repo

Given the example helloworld.proto file. If you add an import statement pointing to one of the well known proto files from the protoc compiler I would expect the example to still work. 
```
syntax = "proto3";

package helloworld;
import "google/protobuf/timestamp.proto";

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```

However the following output is received

```
gateway_1  | 2019/08/01 12:21:26 [alert] 1#1: lua_code_cache is off; this will hurt performance in /etc/nginx/conf.d/server.conf:1
gateway_1  | nginx: [alert] lua_code_cache is off; this will hurt performance in /etc/nginx/conf.d/server.conf:1


gateway_1  | 2019/08/01 12:22:04 [error] 6#6: *1 [lua] util.lua:22: find_method(): /etc/proto/helloworld.proto, client: 172.21.0.1, server: localhost, request: "GET /rest?name=grpc-rest HTTP/1.1", host: "localhost:9000"
gateway_1  | 2019/08/01 12:22:04 [error] 6#6: *1 lua entry thread aborted: runtime error: ...cal/openresty/luajit/share/lua/5.1/grpc-gateway/util.lua:24: attempt to index local 'loaded' (a boolean value)
gateway_1  | stack traceback:
gateway_1  | coroutine 0:
gateway_1  | 	...cal/openresty/luajit/share/lua/5.1/grpc-gateway/util.lua: in function 'find_method'
gateway_1  | 	.../openresty/luajit/share/lua/5.1/grpc-gateway/request.lua:19: in function 'transform'
gateway_1  | 	access_by_lua(server.conf:35):10: in main chunk, client: 172.21.0.1, server: localhost, request: "GET /rest?name=grpc-rest HTTP/1.1", host: "localhost:9000"
gateway_1  | 2019/08/01 12:22:04 [error] 6#6: *1 [lua] util.lua:22: find_method(): /etc/proto/helloworld.proto, client: 172.21.0.1, server: localhost, request: "GET /rest?name=grpc-rest HTTP/1.1", host: "localhost:9000"
gateway_1  | 2019/08/01 12:22:04 [error] 6#6: *1 failed to run body_filter_by_lua*: ...cal/openresty/luajit/share/lua/5.1/grpc-gateway/util.lua:24: attempt to index local 'loaded' (a boolean value)
gateway_1  | stack traceback:
gateway_1  | 	...cal/openresty/luajit/share/lua/5.1/grpc-gateway/util.lua:24: in function 'find_method'
gateway_1  | 	...openresty/luajit/share/lua/5.1/grpc-gateway/response.lua:17: in function 'transform'
gateway_1  | 	body_filter_by_lua:10: in main chunk, client: 172.21.0.1, server: localhost, request: "GET /rest?name=grpc-rest HTTP/1.1", host: "localhost:9000"
gateway_1  | 172.21.0.1 - - [01/Aug/2019:12:22:04 +0000] "GET /rest?name=grpc-rest HTTP/1.1" 500 0 "-" "curl/7.65.3"
```

I think it is because there is an issue in loading the proto file due to the import statement but I am unsure how to further debug this.

**Comment by kgoguevgoget** [comment]
Issue seems to relate to the paths for the "protoc" library found in `proto.lua`. 

When `proto.lua` calls the protoc function `loadfile`, it will fail because the protoc library can not see the dependent proto files. Luckily the protoc libary allows you to set paths. A quick workaround is adding the explicit path to the proto.lua file see code snippet below.

To test this you can copy the google/protobuf folder from /usr/local/include/ to /etc/proto in the docker image for the gateway.

If you installed protoc on your development machine you should also have the well known proto files in /usr/local/include/google. 

Once the docker image for the gateway is up and running 
```
$ ls /etc/proto
drwxr-xr-x 3 root root 4096 Aug  2 07:25 google/protobuf/timestamp.proto
-rw-r--r-- 1 root root  249 Aug  2 11:33 helloworld.proto
```

Since the docker image install protoc via luarocks we do not have any of the well known types in the docker image unless we have copied them.

Import statement Workaround: 

Add the `_p.paths` with both "." and the complete path to the files required for the Import statement. If you omit the "." path then grpc-web will not find the service after the proto file is loaded.

```
 local _p = protoc.new()
    _p.paths = {".","/etc/proto"} 
  -- We'd like to load inside pcall due to prevent duplicate load error
  pcall(function()
    _p:loadfile(proto_file)
  end)
```

**Comment by ysugimoto** [comment]
@kgoguevgoget Thank you for reporting the issue. I'll look into it.

**Comment by ysugimoto** [comment]
@kgoguevgoget Hi, I investigated it and solved that problem. please look at the PR, especially `Import Path` section which I wrote in README.  If you have unclearly point, tell me anything.

**Comment by kgoguevgoget** [comment]
Import paths now seem to work! Thanks for the quick resolution on this issue.
